
@startuml integration

title Интеграция документа "Списание" ( Сборка объекта). Отложенные дозапросы.

actor      DatareonESB order 10
queue      ВходящаяОчередь order 20
Control    ТаблицаПереходныхКлючей order 30
Control    Сборщик order 40
Control    Дозапросы order 50
Control    ОтложенноеПроведение order 60


DatareonESB ->> ВходящаяОчередь : запись пакета №1 320 класса УНИКУМ_Партии\nс данными документа "Партия" из системы "УНИКУМ" 
activate ВходящаяОчередь

group Обработка cообщения 320 класса

    ВходящаяОчередь -> ТаблицаПереходныхКлючей : Поиск элемент справочника **"грОбъекты"** по GUID УНИКУМ
    
    ТаблицаПереходныхКлючей -> ВходящаяОчередь : результата поиска

    create "Инкремент_Партия N \n Справочник.грОбъекты" order 39
    ВходящаяОчередь -> "Инкремент_Партия N \n Справочник.грОбъекты" : создание нового | обновление элемента \n справочника **"грОбъекты"**

    group alt основной объект загружен    
         ВходящаяОчередь -> Сборщик : запуск алгоритма сборки объекта из справочника "Типы объектов".
    end
   

    ВходящаяОчередь -> Дозапросы : формирование дозапросов\nпо недостающим объектам ( отложенный режим ).

    ВходящаяОчередь -> ОтложенноеПроведение : регистрация в очереди отложенного проведения.

end
deactivate ВходящаяОчередь


DatareonESB ->> ВходящаяОчередь : запись пакета №2 \n219 класса ERP_СписаниеНедостачТоваров\nс данными документа "Списание"\n из системы "УНИКУМ" 
activate ВходящаяОчередь

group Обработка cообщения 219 класса

    ВходящаяОчередь -> ТаблицаПереходныхКлючей : Поиск документа **"СписаниеНедостачТоваров"**,\nпоиск элемента справочника"грОбъекты" по GUID УНИКУМ
    
    create "Документ.СписаниеНедостачТоваров" order 39
    ТаблицаПереходныхКлючей -> "Документ.СписаниеНедостачТоваров" : результата поиска

    create "Инкремент_Списание \n Справочник.грОбъекты" order 39
    ВходящаяОчередь -> "Инкремент_Списание \n Справочник.грОбъекты" : запись тела сообщения 219 класса\n  в элемент справочника **"грОбъекты"**.

    ТаблицаПереходныхКлючей -> ВходящаяОчередь : возврат результата поиска

    ВходящаяОчередь -> ВходящаяОчередь :  заполнение документа "СписаниеНедостачТоваров"\nданными из пакета 219 класса

    ВходящаяОчередь -> Сборщик : запуск алгоритма сборки документа "Списание".

    Сборщик -> "Инкремент_Списание \n Справочник.грОбъекты": поиск данных для сборки.
    Сборщик -> "Инкремент_Партия N \n Справочник.грОбъекты" : поиск данных для сборки.
    Сборщик -> ОтложенноеПроведение : регистрация в очереди отложенного\n проведения документа "СписаниеНедостачТоваров".

    ВходящаяОчередь -> Дозапросы : формирование дозапросов\nпо недостающим объектам ( отложенный режим ).

end
deactivate ВходящаяОчередь


Дозапросы -> Дозапросы : отправка дозапросов, повторная обработка пакетов
activate Дозапросы
deactivate Дозапросы

ОтложенноеПроведение -> ОтложенноеПроведение : обработка очереди отложенного проведения,\n проведение документов
activate ОтложенноеПроведение
deactivate ОтложенноеПроведение

@enduml

