
@startuml integration

title Интеграция документа "Списание" ( Сборка объекта). Отложенные дозапросы.

actor      DatareonESB order 10
queue      ВходящаяОчередь order 20
Control    ТаблицаПереходныхКлючей order 30
Control    Сборщик order 40
Control    Дозапросы order 50
Control    ОтложенноеПроведение order 60


DatareonESB ->> ВходящаяОчередь : запись пакета №1 320 класса УНИКУМ_Партии\nс данными документа "Партия" из системы "УНИКУМ"
activate ВходящаяОчередь

group Обработка cообщения 320 класса

    ВходящаяОчередь -> ТаблицаПереходныхКлючей : Поиск элемент справочника **"грОбъекты"** по GUID УНИКУМ

    ТаблицаПереходныхКлючей -> ВходящаяОчередь : результата поиска

    create "Партия N \n Справочник.грОбъекты" order 39
    ВходящаяОчередь -> "Партия N \n Справочник.грОбъекты" : запись инкремента "Партии".

    group alt загружен Документ.СписаниеНедостачТоваров
        ВходящаяОчередь -> Сборщик : запуск алгоритма сборки объекта из справочника "Типы объектов".
        Сборщик -> ОтложенноеПроведение : регистрация Документ.СписаниеНедостачТоваров в очередь отложенного проведения.\nЗапись в регистр сведений "Отложеннное проведение"
    end

    ВходящаяОчередь -> Дозапросы : формирование дозапросов по недостающим объектам ( ненайденные ссылки по GUID УНИКУМ).\nЗапись в РС "Источники дозапросов"

end
deactivate ВходящаяОчередь


DatareonESB ->> ВходящаяОчередь : запись пакета №2 \n219 класса ERP_СписаниеНедостачТоваров\nс данными документа "Списание"\n из системы "УНИКУМ"
activate ВходящаяОчередь

group Обработка cообщения 219 класса

    ВходящаяОчередь -> ТаблицаПереходныхКлючей : Поиск документа **"СписаниеНедостачТоваров"**,\nпоиск элемента справочника"грОбъекты" по GUID УНИКУМ
    ТаблицаПереходныхКлючей -> ВходящаяОчередь : результата поиска
    create "Документ.СписаниеНедостачТоваров" order 39
    ВходящаяОчередь -> "Документ.СписаниеНедостачТоваров" : создание Документ.СписаниеНедостачТоваров

    create "Списание \n Справочник.грОбъекты" order 39
    ВходящаяОчередь -> "Списание \n Справочник.грОбъекты" : запись инкремента "Списание".

    ТаблицаПереходныхКлючей -> ВходящаяОчередь : возврат результата поиска

    ВходящаяОчередь -> ВходящаяОчередь :  заполнение документа "СписаниеНедостачТоваров"\nданными из пакета 219 класса

    group alt загружен Документ.СписаниеНедостачТоваров
        ВходящаяОчередь -> Сборщик : запуск алгоритма сборки документа "Списание".\n С учетом загруженной цепочки документов.

        activate Сборщик
        Сборщик -> "Списание \n Справочник.грОбъекты": поиск данных для сборки.
        Сборщик -> "Партия N \n Справочник.грОбъекты" : поиск данных для сборки.
        Сборщик -> "Документ.СписаниеНедостачТоваров" : запись результат сборки в Документ.СписаниеНедостачТоваров.
        Сборщик -> ОтложенноеПроведение : регистрация Документ.СписаниеНедостачТоваров в очередь отложенного проведения.\nЗапись в регистр сведений "Отложеннное проведение"
        deactivate Сборщик
        ВходящаяОчередь -> Дозапросы : формирование дозапросов\nпо недостающим объектам ( отложенный режим ).
    end
end
deactivate ВходящаяОчередь

DatareonESB ->> ВходящаяОчередь : запись пакета №3 335 класса УНИКУМ_СправкиБ\nс данными документа "СправкаБ" из системы "УНИКУМ"
activate ВходящаяОчередь

group Обработка cообщения 335 класса

    ВходящаяОчередь -> ТаблицаПереходныхКлючей : Поиск элемент справочника **"грОбъекты"** по GUID УНИКУМ

    ТаблицаПереходныхКлючей -> ВходящаяОчередь : результата поиска

    create "СправкаБ N \n Справочник.грОбъекты" order 39
    ВходящаяОчередь -> "СправкаБ N \n Справочник.грОбъекты" : запись инкремента "СправкаБ".

    group alt загружен Документ.СписаниеНедостачТоваров

        ВходящаяОчередь -> Сборщик : запуск алгоритма сборки объекта из справочника "Типы объектов".\n С учетом загруженной цепочки документов.
        activate Сборщик
        Сборщик -> "Списание \n Справочник.грОбъекты": поиск данных для сборки.
        Сборщик -> "Партия N \n Справочник.грОбъекты" : поиск данных для сборки.
        Сборщик -> "СправкаБ N \n Справочник.грОбъекты" : поиск данных для сборки.
        Сборщик -> "Документ.СписаниеНедостачТоваров" : запись результат сборки в Документ.СписаниеНедостачТоваров.
        Сборщик -> ОтложенноеПроведение : регистрация Документ.СписаниеНедостачТоваров в очередь отложенного проведения.\nЗапись в регистр сведений "Отложеннное проведение"
        deactivate Сборщик
    end

    ВходящаяОчередь -> Дозапросы : формирование дозапросов по недостающим объектам ( ненайденные ссылки по GUID УНИКУМ).\nЗапись в РС "Источники дозапросов"

end
deactivate ВходящаяОчередь


Дозапросы ->>  DatareonESB : отправка дозапросов.
activate Дозапросы
deactivate Дозапросы

DatareonESB ->> Дозапросы : отправка ответов на дозапросы.
activate Дозапросы
deactivate Дозапросы

Дозапросы ->> Дозапросы : обработка пакетов по полученным дозапросам.\nОбработка записей РС "Источники дозапросов".
activate Дозапросы
deactivate Дозапросы

ОтложенноеПроведение ->> ОтложенноеПроведение : обработка очереди отложенного проведения,\n проведение документов
activate ОтложенноеПроведение
deactivate ОтложенноеПроведение

@enduml

