
@startuml integration

title Интеграция Сделок.

actor      DatareonESB order 10
queue      ВходящаяОчередь order 20
Control    ТаблицаПереходныхКлючей order 30
Control    Дозапросы order 50
Control    ЗаданияОтложеннойОбработкиДанных order 70

DatareonESB ->> ВходящаяОчередь : запись сообщения ESB
activate ВходящаяОчередь

group Обработка cообщения

    ВходящаяОчередь -> ЗаданияОтложеннойОбработкиДанных : поиск не обработанных объектов.
    ЗаданияОтложеннойОбработкиДанных -> ВходящаяОчередь : перечень обработанных объектов.

    group loop

        ВходящаяОчередь -> ТаблицаПереходныхКлючей : Поиск объекта.

        ТаблицаПереходныхКлючей -> ВходящаяОчередь :  результат поиска

        ВходящаяОчередь -> ВходящаяОчередь :  заполнение объекта данными из сообщения.

    end

    group alt требуется сформировать дозапросы по недостающим

        ВходящаяОчередь -> Дозапросы : отправка дозапросов\n по недостающим объектам.
        ВходящаяОчередь -> ВходящаяОчередь : откладывание сообщения для повторной обработки.

    end

    ВходящаяОчередь -> ЗаданияОтложеннойОбработкиДанных : регистрация обработанных объектов.

end
deactivate ВходящаяОчередь

@enduml

