
@startuml integration

title Интеграция документа "Списание товаров" ( Сборка инкрементов ). Отложенные дозапросы.

actor      DatareonESB order 10
queue      ВходящаяОчередь order 20
Control    ТаблицаПереходныхКлючей order 30
Control    Сборщик order 40
Control    Дозапросы order 50
Control    ОтложенноеПроведение order 60



DatareonESB ->> ВходящаяОчередь : запись сообщения ESB
activate ВходящаяОчередь

group Обработка cообщения

    ВходящаяОчередь -> ТаблицаПереходныхКлючей : Поиск основного объекта.\nПоиск инкремента объекта.

    ТаблицаПереходныхКлючей -> Сборщик : формирование /обновление\nинкремента объекта.

    ТаблицаПереходныхКлючей -> ВходящаяОчередь :  результат поиска

    ВходящаяОчередь -> ВходящаяОчередь :  заполнение основного\nобъекта данными из сообщения

    ВходящаяОчередь -> Сборщик : запуск алгоритма сборки объекта из инкрементов.

    ВходящаяОчередь -> Дозапросы : формирование дозапросов\nпо недостающим объектам ( отложенный режим ).

    ВходящаяОчередь -> ОтложенноеПроведение : регистрация в очереди отложенного проведения.

end
deactivate ВходящаяОчередь

Дозапросы -> Дозапросы : отправка дозапросов, повторная обработка пакетов
activate Дозапросы
deactivate Дозапросы

ОтложенноеПроведение -> ОтложенноеПроведение : обработка очереди отложенного проведения,\n проведение документов
activate ОтложенноеПроведение
deactivate ОтложенноеПроведение

@enduml

